train:
  _target_: src.datasets.libri_tts_dataset.LibriTTSDataset
  root_dir: ${hydra:runtime.cwd}/data/LibriTTS
  subsets: ["train-clean-100"]
  part: train
  val_ratio: 0.1
  test_ratio: 0.1
  split_seed: 42
  segment_size: 16384
  sample_rate: 22050
  n_fft: 1024
  hop_length: 256
  n_mels: 80
  f_min: 0.0
  f_max: 8000.0
  min_duration_sec: 0.5
  max_duration_sec: null
  max_files_per_speaker: null
  limit: null
  shuffle_index: true

val:
  _target_: src.datasets.libri_tts_dataset.LibriTTSDataset
  root_dir: ${datasets.train.root_dir}
  subsets: ${datasets.train.subsets}
  part: val
  val_ratio: ${datasets.train.val_ratio}
  test_ratio: ${datasets.train.test_ratio}
  split_seed: ${datasets.train.split_seed}
  segment_size: ${datasets.train.segment_size}
  sample_rate: ${datasets.train.sample_rate}
  n_fft: ${datasets.train.n_fft}
  hop_length: ${datasets.train.hop_length}
  n_mels: ${datasets.train.n_mels}
  f_min: ${datasets.train.f_min}
  f_max: ${datasets.train.f_max}
  min_duration_sec: ${datasets.train.min_duration_sec}
  max_duration_sec: ${datasets.train.max_duration_sec}
  limit: 500
  shuffle_index: true

test:
  _target_: src.datasets.libri_tts_dataset.LibriTTSDataset
  root_dir: ${datasets.train.root_dir}
  subsets: ${datasets.train.subsets}
  part: test
  val_ratio: ${datasets.train.val_ratio}
  test_ratio: ${datasets.train.test_ratio}
  split_seed: ${datasets.train.split_seed}
  segment_size: ${datasets.train.segment_size}
  sample_rate: ${datasets.train.sample_rate}
  n_fft: ${datasets.train.n_fft}
  hop_length: ${datasets.train.hop_length}
  n_mels: ${datasets.train.n_mels}
  f_min: ${datasets.train.f_min}
  f_max: ${datasets.train.f_max}
  min_duration_sec: ${datasets.train.min_duration_sec}
  max_duration_sec: ${datasets.train.max_duration_sec}
  limit: 600
  shuffle_index: true
